apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: exbot 
  janus-idp.io/tekton: exbot
  backstage.io/kubernetes-id: exbot
  backstage.io/kubernetes-namespace: ai-rhdh-app-development 
  app.kubernetes.io/part-of: exbot
resources: 
- application-dev.yaml