apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: exbot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: exbot 
  name: exbot
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: exbot 
    weight: 100 
  wildcardPolicy: None
